import { useState, useEffect } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { useTerminal } from '../contexts/TerminalContext';
import Navbar from '../components/Navbar';
import './Documents.css';

function Documents() {
  const [documents, setDocuments] = useState(null);
  const [activeTab, setActiveTab] = useState('vision');
  const [editing, setEditing] = useState(false);
  const [editContent, setEditContent] = useState('');
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const { token } = useAuth();
  const { terminalLogs } = useTerminal();

  useEffect(() => {
    fetchDocuments();
  }, []);

  const fetchDocuments = async () => {
    try {
      const response = await fetch('/api/documents', {
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      const data = await response.json();

      if (response.ok) {
        setDocuments(data.documents);
      } else {
        setError(data.message || 'Failed to load documents');
      }
    } catch (err) {
      setError('Failed to load documents. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const startEditing = () => {
    const content = activeTab === 'vision' ? documents.vision_md : documents.goals_md;
    setEditContent(content);
    setEditing(true);
  };

  const cancelEditing = () => {
    setEditing(false);
    setEditContent('');
  };

  const saveDocument = async () => {
    setSaving(true);
    setError('');

    try {
      const response = await fetch(`/api/documents/${activeTab}`, {
        method: 'PUT',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ content: editContent })
      });

      const data = await response.json();

      if (response.ok) {
        // Update local state
        setDocuments({
          ...documents,
          [`${activeTab}_md`]: editContent,
          updated_at: data.document.updated_at
        });
        setEditing(false);
        setEditContent('');
        alert('Document saved successfully!');
      } else {
        setError(data.message || 'Failed to save document');
        alert('Failed to save document: ' + (data.message || 'Unknown error'));
      }
    } catch (err) {
      setError('Failed to save document. Please try again.');
      alert('Failed to save document. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const formatLogMessage = (log) => {
    const time = new Date(log.timestamp).toLocaleTimeString();
    return `[${time}] ${log.stage ? `[${log.stage}] ` : ''}${log.message}`;
  };

  const displayLogs = terminalLogs.slice(-4);

  const getTabContent = () => {
    if (!documents) return '';

    switch (activeTab) {
      case 'vision':
        return documents.vision_md;
      case 'goals':
        return documents.goals_md;
      case 'analytics':
        return documents.analytics_md;
      case 'memory':
        return documents.memory_md;
      default:
        return '';
    }
  };

  const canEdit = activeTab === 'vision' || activeTab === 'goals';

  return (
    <div className="documents-container">
      <div className="terminal">
        {displayLogs.length === 0 ? (
          <>
            <div>&gt; Document Store Manager</div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
            <div>&nbsp;</div>
          </>
        ) : (
          <>
            {displayLogs.map((log, index) => (
              <div key={`${log.id}-${index}`}>&gt; {formatLogMessage(log)}</div>
            ))}
            {displayLogs.length < 4 &&
              Array.from({ length: 4 - displayLogs.length }).map((_, i) => (
                <div key={`empty-${i}`}>&nbsp;</div>
              ))
            }
          </>
        )}
      </div>

      <Navbar />

      <div className="documents-content">
        {loading && (
          <div className="status-message">
            <p>Loading documents...</p>
          </div>
        )}

        {error && !loading && (
          <div className="status-message error">
            <p>{error}</p>
          </div>
        )}

        {!loading && documents && (
          <>
            <div className="documents-header">
              <h1>📄 Company Documents</h1>
              <p className="documents-subtitle">
                Manage your company's vision, goals, and view analytics generated by the Brain.
              </p>
            </div>

            {/* Tab Navigation */}
            <div className="tab-navigation">
              <button
                className={`tab-button ${activeTab === 'vision' ? 'active' : ''}`}
                onClick={() => { setActiveTab('vision'); setEditing(false); }}
              >
                🎯 Vision
              </button>
              <button
                className={`tab-button ${activeTab === 'goals' ? 'active' : ''}`}
                onClick={() => { setActiveTab('goals'); setEditing(false); }}
              >
                🎯 Goals
              </button>
              <button
                className={`tab-button ${activeTab === 'analytics' ? 'active' : ''}`}
                onClick={() => { setActiveTab('analytics'); setEditing(false); }}
              >
                📊 Analytics
              </button>
              <button
                className={`tab-button ${activeTab === 'memory' ? 'active' : ''}`}
                onClick={() => { setActiveTab('memory'); setEditing(false); }}
              >
                🧠 Memory
              </button>
            </div>

            {/* Document Content */}
            <div className="document-viewer">
              <div className="document-header">
                <h2>{activeTab.charAt(0).toUpperCase() + activeTab.slice(1)}</h2>
                <div className="document-actions">
                  {canEdit && !editing && (
                    <button className="edit-button" onClick={startEditing}>
                      Edit
                    </button>
                  )}
                  {editing && (
                    <>
                      <button className="cancel-button" onClick={cancelEditing}>
                        Cancel
                      </button>
                      <button
                        className="save-button"
                        onClick={saveDocument}
                        disabled={saving}
                      >
                        {saving ? 'Saving...' : 'Save'}
                      </button>
                    </>
                  )}
                  {!canEdit && (
                    <span className="read-only-badge">Read-only (Auto-managed by Brain)</span>
                  )}
                </div>
              </div>

              {editing ? (
                <textarea
                  className="document-editor"
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  placeholder={`Enter your company's ${activeTab}...`}
                />
              ) : (
                <div className="document-content">
                  {getTabContent() ? (
                    <pre>{getTabContent()}</pre>
                  ) : (
                    <p className="empty-state">No content yet. {canEdit && 'Click Edit to get started!'}</p>
                  )}
                </div>
              )}

              {activeTab === 'analytics' && documents.analytics_json && Object.keys(documents.analytics_json).length > 0 && (
                <details className="analytics-json">
                  <summary>View Structured Data (JSON)</summary>
                  <pre>{JSON.stringify(documents.analytics_json, null, 2)}</pre>
                </details>
              )}
            </div>

            {documents.updated_at && (
              <div className="document-footer">
                Last updated: {new Date(documents.updated_at).toLocaleString()}
              </div>
            )}
          </>
        )}
      </div>

      <footer className="footer">
        <p className="footer-contact">Contact: <a href="mailto:system@polsia.ai">system@polsia.ai</a></p>
      </footer>
    </div>
  );
}

export default Documents;
